analysis:
  title: DiD | Midl. lønnstilskudd | Situasjonsbestemt | Faktisk | Kontinuerlig
  treatment_start: '202506'
  data_start: '202306'
  data_end: '202512'
  treatment_type: continuous
  variation: did/midl-lonnstilskudd/regioner
  denominator_definitions:
  - id: last_pre
    label: Siste pre-måned (t-1)
data:
  tiltak_file: data/input/tiltak/midl.-lønnstilskudd.csv
  tiltak_label: Midlertidig lønnstilskudd
  indikatorer:
  - name: atid3
    file: data/input/indikatorer/nedbrytning/situasjonsbestemt/faktisk_atid3.csv
    description: Arbeidstid neste tre måneder
  - name: jobb3
    file: data/input/indikatorer/nedbrytning/situasjonsbestemt/faktisk_jobb3.csv
    description: I jobb etter 3 måneder
