analysis:
  title: TrippelDiD | Midl. lønnstilskudd | Enheter | Kontinuerlig
  treatment_start: '202506'
  data_start: '202306'
  data_end: '202512'
  treatment_type: continuous
  variation: triple-diff/midl-lonnstilskudd/enheter
  design: triple_diff
  analysis_level: enhet
  treated_group: Veiledning kombinert
  control_group: Standard
  denominator_definitions:
  - id: last_pre
    label: Siste pre-måned (t-1)
data:
  tiltak_file: data/input/tiltak/alle-tiltak.csv
  tiltak_label: Alle tiltak
  enhet_mapping_file: data/input/støttedata/enhetsmapping.json
  indikatorer:
  - name: atid3
    group: treated
    file: data/input/indikatorer/enhet/nedbrytning/veiledning_kombinert/atid3.csv
    description: Arbeidstid neste tre måneder (Veiledning kombinert, enheter)
  - name: atid3
    group: control
    file: data/input/indikatorer/enhet/nedbrytning/standard/atid3.csv
    description: Arbeidstid neste tre måneder (Standard, enheter)
  - name: jobb3
    group: treated
    file: data/input/indikatorer/enhet/nedbrytning/veiledning_kombinert/jobb3.csv
    description: I jobb etter 3 måneder (Veiledning kombinert, enheter)
  - name: jobb3
    group: control
    file: data/input/indikatorer/enhet/nedbrytning/standard/jobb3.csv
    description: I jobb etter 3 måneder (Standard, enheter)
