analysis:
  title: DiD | Midl. lønnstilskudd | Veiledning kombinert | Diskret (Enheter)
  treatment_start: '202506'
  data_start: '202306'
  data_end: '202512'
  treatment_type: discrete
  variation: did/midl-lonnstilskudd/enheter
  analysis_level: enhet
  control_regions:
  - Nav Innlandet
  - Nav Nordland
data:
  tiltak_file: data/input/tiltak/midl.-lønnstilskudd.csv
  tiltak_label: Midlertidig lønnstilskudd
  indikatorer:
  - name: atid3
    file: data/input/indikatorer/enhet/nedbrytning/veiledning_kombinert/atid3.csv
    description: Arbeidstid neste tre måneder
  - name: jobb3
    file: data/input/indikatorer/enhet/nedbrytning/veiledning_kombinert/jobb3.csv
    description: I jobb etter 3 måneder
  enhet_mapping_file: data/input/støttedata/enhetsmapping.json
