analysis:
  title: DiD | Midl. lønnstilskudd | Spesielt tilpasset | Faktisk | Kontinuerlig (Enheter)
  treatment_start: '202506'
  data_start: '202306'
  data_end: '202512'
  treatment_type: continuous
  variation: did/midl-lonnstilskudd/enheter
  analysis_level: enhet
  denominator_definitions:
  - id: last_pre
    label: Siste pre-måned (t-1)
data:
  tiltak_file: data/input/tiltak/midl.-lønnstilskudd.csv
  tiltak_label: Midlertidig lønnstilskudd
  indikatorer:
  - name: atid3
    file: data/input/indikatorer/enhet/nedbrytning/spesielt_tilpasset/faktisk_atid3.csv
    description: Arbeidstid neste tre måneder
  - name: jobb3
    file: data/input/indikatorer/enhet/nedbrytning/spesielt_tilpasset/faktisk_jobb3.csv
    description: I jobb etter 3 måneder
  enhet_mapping_file: data/input/støttedata/enhetsmapping.json
