project:
  type: book
  output-dir: _book
date: now
date-format: DD.MM.YYYY
author-title: Eier
book:
  title: 'DiD-analyser: effekt av tiltaksnedgang'
  description: Arbeidsdokumenter for difference-in-differences-analyser av effekten
    av tiltaksnedgang i Nav
  author: Jacob Sjødin
  chapters:
  - index.qmd
  - part: regioner/intro.qmd
    chapters:
    - regioner/alle-discrete/report_alle-discrete.qmd
    - regioner/alle-kontinuerlig/report_alle-kontinuerlig.qmd
    - regioner/faktisk-alle-kontinuerlig/report_faktisk-alle-kontinuerlig.qmd
    - regioner/faktisk-gode-muligheter-kontinuerlig/report_faktisk-gode-muligheter-kontinuerlig.qmd
    - regioner/faktisk-nedsatt-arbeidsevne-kontinuerlig/report_faktisk-nedsatt-arbeidsevne-kontinuerlig.qmd
    - regioner/faktisk-trenger-veiledning-kontinuerlig/report_faktisk-trenger-veiledning-kontinuerlig.qmd
    - regioner/forventet-alle-kontinuerlig/report_forventet-alle-kontinuerlig.qmd
    - regioner/forventet-gode-muligheter-kontinuerlig/report_forventet-gode-muligheter-kontinuerlig.qmd
    - regioner/forventet-nedsatt-arbeidsevne-kontinuerlig/report_forventet-nedsatt-arbeidsevne-kontinuerlig.qmd
    - regioner/forventet-trenger-veiledning-kontinuerlig/report_forventet-trenger-veiledning-kontinuerlig.qmd
    - regioner/gode-muligheter-discrete/report_gode-muligheter-discrete.qmd
    - regioner/gode-muligheter-kontinuerlig/report_gode-muligheter-kontinuerlig.qmd
    - regioner/nedsatt-arbeidsevne-discrete/report_nedsatt-arbeidsevne-discrete.qmd
    - regioner/nedsatt-arbeidsevne-kontinuerlig/report_nedsatt-arbeidsevne-kontinuerlig.qmd
    - regioner/trenger-veiledning-discrete/report_trenger-veiledning-discrete.qmd
    - regioner/trenger-veiledning-kontinuerlig/report_trenger-veiledning-kontinuerlig.qmd
  - part: trippel-diff-regioner-kontinuerlig/intro.qmd
    chapters:
    - trippel-diff-regioner-kontinuerlig/01-deskriptiv.qmd
    - trippel-diff-regioner-kontinuerlig/02-regresjonsresultater.qmd
    - trippel-diff-regioner-kontinuerlig/03-bootstrap.qmd
    - trippel-diff-regioner-kontinuerlig/04-antagelser.qmd
  - part: trippel-diff-enheter-kontinuerlig/intro.qmd
    chapters:
    - trippel-diff-enheter-kontinuerlig/01-deskriptiv.qmd
    - trippel-diff-enheter-kontinuerlig/02-regresjonsresultater.qmd
    - trippel-diff-enheter-kontinuerlig/03-bootstrap.qmd
    - trippel-diff-enheter-kontinuerlig/04-antagelser.qmd
  page-navigation: true
  page-footer: Nav - {{< meta date >}}
  repo-url: https://github.com/navikt/arbind-tiltak-did
  reader-mode: false
  search: true
  navbar:
    logo: assets/nav_logo_hvit.png
    logo-alt: Logo til Nav - Arbeids- og velferdsetaten
format:
  html:
    lang: nb
    toc: true
    toc-depth: 3
    theme:
      light: flatly
      dark: darkly
