project:
  type: book
  output-dir: _book
date: now
date-format: DD.MM.YYYY
author-title: Eier
book:
  title: 'DiD-analyser: effekt av tiltaksnedgang'
  description: Arbeidsdokumenter for difference-in-differences-analyser av effekten
    av tiltaksnedgang i Nav
  author: Jacob Sjødin
  chapters:
  - index.qmd
  - part: data/intro.qmd
    chapters:
    - data/tiltak-midl-lonnstilskudd.qmd
    - data/tiltak-alle-tiltak.qmd
    - data/indikatorer.qmd
  - part: did/midl-lonnstilskudd/intro.qmd
    chapters:
    - did/midl-lonnstilskudd/alle--diskret/report_alle--diskret.qmd
    - did/midl-lonnstilskudd/alle--faktisk-kontinuerlig/report_alle--faktisk-kontinuerlig.qmd
    - did/midl-lonnstilskudd/alle--forventet-kontinuerlig/report_alle--forventet-kontinuerlig.qmd
    - did/midl-lonnstilskudd/standard--kontinuerlig/report_standard--kontinuerlig.qmd
    - did/midl-lonnstilskudd/standard--diskret/report_standard--diskret.qmd
    - did/midl-lonnstilskudd/standard--faktisk-kontinuerlig/report_standard--faktisk-kontinuerlig.qmd
    - did/midl-lonnstilskudd/standard--forventet-kontinuerlig/report_standard--forventet-kontinuerlig.qmd
    - did/midl-lonnstilskudd/situasjonsbestemt--kontinuerlig/report_situasjonsbestemt--kontinuerlig.qmd
    - did/midl-lonnstilskudd/situasjonsbestemt--diskret/report_situasjonsbestemt--diskret.qmd
    - did/midl-lonnstilskudd/situasjonsbestemt--faktisk-kontinuerlig/report_situasjonsbestemt--faktisk-kontinuerlig.qmd
    - did/midl-lonnstilskudd/situasjonsbestemt--forventet-kontinuerlig/report_situasjonsbestemt--forventet-kontinuerlig.qmd
    - did/midl-lonnstilskudd/spesielt-tilpasset--diskret/report_spesielt-tilpasset--diskret.qmd
    - did/midl-lonnstilskudd/spesielt-tilpasset--faktisk-kontinuerlig/report_spesielt-tilpasset--faktisk-kontinuerlig.qmd
    - did/midl-lonnstilskudd/spesielt-tilpasset--forventet-kontinuerlig/report_spesielt-tilpasset--forventet-kontinuerlig.qmd
  - part: did/alle-tiltak/intro.qmd
    chapters:
    - did/alle-tiltak/alle--kontinuerlig/report_alle--kontinuerlig.qmd
    - did/alle-tiltak/spesielt-tilpasset--kontinuerlig/report_spesielt-tilpasset--kontinuerlig.qmd
    - did/alle-tiltak/veiledning-kombinert--kontinuerlig/report_veiledning-kombinert--kontinuerlig.qmd
  - part: triple-diff/midl-lonnstilskudd/regioner/intro.qmd
    chapters:
    - triple-diff/midl-lonnstilskudd/regioner/01-deskriptiv.qmd
    - triple-diff/midl-lonnstilskudd/regioner/02-regresjonsresultater.qmd
    - triple-diff/midl-lonnstilskudd/regioner/03-bootstrap.qmd
    - triple-diff/midl-lonnstilskudd/regioner/04-antagelser.qmd
  - part: triple-diff/midl-lonnstilskudd/enheter/intro.qmd
    chapters:
    - triple-diff/midl-lonnstilskudd/enheter/01-deskriptiv.qmd
    - triple-diff/midl-lonnstilskudd/enheter/02-regresjonsresultater.qmd
    - triple-diff/midl-lonnstilskudd/enheter/03-bootstrap.qmd
    - triple-diff/midl-lonnstilskudd/enheter/04-antagelser.qmd
  page-navigation: true
  page-footer: Nav - {{< meta date >}}
  repo-url: https://github.com/navikt/arbind-tiltak-did
  reader-mode: false
  search: true
  navbar:
    logo: assets/nav_logo_hvit.png
    logo-alt: Logo til Nav - Arbeids- og velferdsetaten
format:
  html:
    lang: nb
    toc: true
    toc-depth: 3
    theme:
      light: flatly
      dark: darkly
