analysis:
  title: DiD | Alle tiltak | Veiledning kombinert | Kontinuerlig
  treatment_start: '202506'
  data_start: '202306'
  data_end: '202512'
  treatment_type: continuous
  variation: did/alle-tiltak/regioner
  analysis_level: region
  denominator_definitions:
  - id: last_pre
    label: Siste pre-måned (t-1)
data:
  tiltak_file: data/input/tiltak/alle-tiltak.csv
  tiltak_label: Alle tiltak
  tiltak_seasonal_adjust: true
  indikatorer:
  - name: atid3
    file: data/input/indikatorer/nedbrytning/veiledning_kombinert/atid3.csv
    description: Arbeidstid neste tre måneder
  - name: jobb3
    file: data/input/indikatorer/nedbrytning/veiledning_kombinert/jobb3.csv
    description: I jobb etter 3 måneder
