name: Bygg rapporter og publiser på Datamarkedsplassen

on:
  push:
    branches:
        - main
    paths:
        - 'quarto/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v6
      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Render project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: quarto/
      - name: Last opp til Datamarkedsplassen
        uses: navikt/story-upload@v2
        with:
          id: a950f977-6423-4061-86da-c7c98c56bfcf
          dir: quarto/_book
          team_id: ${{ secrets.TEAM_ID }}
          team_token: ${{ secrets.TEAM_TOKEN_PROD }}
          env: prod
          public: false
